apiVersion: v1
kind: Service
metadata:
  name: graphql
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  graphql_mapping
      prefix: /graphql/
      service: graphql
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: graphql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
spec:
  selector:
    matchLabels:
      app: graphql
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: graphql
        version: '12'
    spec:
      containers:
      - name: graphql
        image: jasonblanchard/multisvc-graphql:12
        env:
          - name: 'PORT'
            value: '80'
          - name: 'WIDGET_AUTHORING_SERVICE_PRESENTER_PATH'
            value: 'http://widget-authoring-presenter/graphql'
          - name: 'STAR_RATING_PRESENTER_PATH'
            value: 'http://star-rating-presenter/graphql'
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
             path: /health
             port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1