apiVersion: v1
kind: Service
metadata:
  name: echo
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  echo_mapping
      prefix: /echo/
      service: echo:8080
  labels:
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: echo
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app: echo
spec:
  selector:
    matchLabels:
      app: echo
      tier: frontend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: echo
        tier: frontend
    spec:
      containers:
      - name: echo
        image: jasonblanchard/multisvc-echo:5
        env:
          - name: 'PORT'
            value: '8080'
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
             path: /health
             port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1