apiVersion: v1
kind: Service
metadata:
  name: echo
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  echo_mapping
      prefix: /echo/
      service: echo
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  selector:
    matchLabels:
      app: echo
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: jasonblanchard/multisvc-echo:6
        env:
          - name: 'PORT'
            value: '80'
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
             path: /health
             port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1