apiVersion: v1
kind: Service
metadata:
  name: widget-authoring
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: widget-authoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: widget-authoring
spec:
  selector:
    matchLabels:
      app: widget-authoring
  replicas: 1
  template:
    metadata:
      labels:
        app: widget-authoring
    spec:
      containers:
      - name: widget-authoring
        image: jasonblanchard/multisvc-widget-authoring:1
        env:
          - name: 'PORT'
            value: '80'
        ports:
        - containerPort: 80