apiVersion: v1
kind: Service
metadata:
  name: auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: AuthService
      name: authentication
      auth_service: "auth"
      path_prefix:  "/session/authn"
      proto: http
      allow_request_body: true
      allowed_request_headers:
        - "CSRF-Token"
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  auth_mapping
      prefix: /auth/
      service: auth
      bypass_auth: true
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1 # Important until implement RedisStore for sessions
  template:
    metadata:
      labels:
        app: auth
        version: '11'
    spec:
      containers:
      - name: auth
        image: jasonblanchard/multisvc-auth:11
        env:
          - name: 'PORT'
            value: '80'
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
             path: /health
             port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1