apiVersion: v1
kind: Service
metadata:
  name: auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: AuthService
      name: authentication
      auth_service: "auth:8081"
      path_prefix:  "/session"
      proto: http
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  auth_mapping
      prefix: /auth/
      service: auth:8081
      bypass_auth: true
  labels:
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - port: 8081
  selector:
    app: auth
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
      tier: frontend
  replicas: 1 # Important until implement RedisStore for sessions
  template:
    metadata:
      labels:
        app: auth
        tier: frontend
    spec:
      containers:
      - name: auth
        image: jasonblanchard/multisvc-auth:6
        env:
          - name: 'PORT'
            value: '8081'
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
             path: /health
             port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1